# Process config example for dataset

# global parameters
project_name: 'dedup'
dataset_path: '/root/TheGodOfCookery/eval/conversations_dedup.jsonl'  # path to your dataset directory or file
np: 8  # number of subprocess to process your dataset
text_keys: 'output'
open_tracer: true
trace_num: 1000
op_fusion: true

export_path: '/root/TheGodOfCookery/eval/conversations_dedup_output.jsonl'


# process schedule
# a list of several process operators with their arguments
process:
  # - language_id_score_filter:
  #     lang: en
  #     min_score: 0.5
#  - document_deduplicator:
#      lowercase: false
#      ignore_non_character: false
  - document_minhash_deduplicator:
      tokenization: 'character'
  - document_simhash_deduplicator:
      tokenization: 'character'

      